### ISSUE TITLE
Doesn't work with pacman

### ISSUE THREAD

**Issue by mukul-mehta** [joehillen/paruz#2]
I tried running paruz with just pacman and no other AUR helper and it fails to run. On exiting, the error is ```sudo pacman: no such command found```. I'm running:

- bash: 5.1.18
- fzf: 0.27.2

![image](https://user-images.githubusercontent.com/43145555/135838350-85a5f827-a92f-4fcf-af4a-5bcb02ebe1d6.png)

**Comment by joehillen** [comment]
Should be fixed in the latest master. Let me know.

This is the first I've heard of  MSYS2. Awesome that it uses pacman. If I'm ever forced to use Windows again, I'll definitely try it out. Thanks!
