### ISSUE TITLE
Links are not clickable

### ISSUE THREAD

**Issue by drod3763** [joehillen/paruz#5]
The links in the info panel do not work when clicked for me in kitty. Sometimes I like to view the comments in an AUR package before install, and would like to be able to click the URL.

**Comment by joehillen** [comment]
I don't think that is something I can fix. It might be an issue with kitty. I think kitty might be ignoring links when the tty is in [raw](https://linux.die.net/man/3/raw) mode. Do you have an example of links working in a terminal UI?
